import { useState } from "react";
import { Card } from "../../components/ui/Card";
import { Button } from "../../components/ui/Button";
import { SectionHeader } from "../../components/common/States";

const suggestedPrompts = [
  "Which leads should I contact today?",
  "Which deals need attention?",
  "What should I prioritize?",
  "Show my highest-value opportunities.",
];

const demoResponses: Record<string, string> = {
  "Which leads should I contact today?":
    "Based on your pipeline, 4 leads haven't been contacted in over a week. Prioritize hot-scored leads first — they're most likely to convert.",
  "Which deals need attention?":
    "3 deals in Negotiation have passed their expected close date. A quick check-in call could help re-accelerate them.",
  "What should I prioritize?":
    "Focus on overdue follow-ups first, then move qualified leads into Proposal stage — that's where most of your pipeline value is currently sitting.",
  "Show my highest-value opportunities.":
    "Your top opportunities are concentrated in the Proposal and Negotiation stages. Consider allocating more time there this week.",
};

interface Message {
  role: "user" | "assistant";
  text: string;
}

export function CopilotPage() {
  const [messages, setMessages] = useState<Message[]>([
    { role: "assistant", text: "Hi! I'm FLOW AI. Ask me about your leads, deals, or what to prioritize today." },
  ]);
  const [input, setInput] = useState("");

  function send(text: string) {
    if (!text.trim()) return;
    const reply =
      demoResponses[text] ??
      "This is a preview of FLOW AI. In this version, responses are sample content — a real AI-powered assistant is on our roadmap.";
    setMessages((prev) => [...prev, { role: "user", text }, { role: "assistant", text: reply }]);
    setInput("");
  }

  return (
    <div>
      <SectionHeader
        title="AI Copilot"
        subtitle="A preview of FLOW's upcoming AI-powered sales assistant."
      />

      <div style={{ marginBottom: 14 }}>
        <span style={{ fontSize: 11.5, color: "var(--text-tertiary)", background: "var(--bg-elevated)", border: "1px solid var(--border)", padding: "4px 10px", borderRadius: 999 }}>
          Preview feature — responses are sample content, not generated by a live AI model
        </span>
      </div>

      <Card style={{ display: "flex", flexDirection: "column", height: 520, padding: 0, overflow: "hidden" }}>
        <div style={{ flex: 1, overflowY: "auto", padding: 20, display: "flex", flexDirection: "column", gap: 12 }} className="scrollbar-thin">
          {messages.map((m, i) => (
            <div
              key={i}
              style={{
                alignSelf: m.role === "user" ? "flex-end" : "flex-start",
                maxWidth: "78%",
                background: m.role === "user" ? "linear-gradient(135deg, var(--accent), #7c3aed)" : "var(--bg-elevated)",
                color: m.role === "user" ? "#fff" : "var(--text-primary)",
                padding: "10px 14px",
                borderRadius: "var(--radius-lg)",
                fontSize: 13.5,
                lineHeight: 1.5,
              }}
            >
              {m.text}
            </div>
          ))}
        </div>

        <div style={{ borderTop: "1px solid var(--border)", padding: 14 }}>
          <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 10 }}>
            {suggestedPrompts.map((p) => (
              <button
                key={p}
                onClick={() => send(p)}
                style={{
                  fontSize: 12,
                  padding: "6px 12px",
                  borderRadius: 999,
                  border: "1px solid var(--border)",
                  background: "var(--bg-elevated)",
                  color: "var(--text-secondary)",
                  cursor: "pointer",
                }}
              >
                {p}
              </button>
            ))}
          </div>
          <form
            onSubmit={(e) => {
              e.preventDefault();
              send(input);
            }}
            style={{ display: "flex", gap: 8 }}
          >
            <input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ask FLOW AI…"
              style={{
                flex: 1,
                padding: "10px 14px",
                borderRadius: "var(--radius-md)",
                border: "1px solid var(--border)",
                background: "var(--bg-elevated)",
                color: "var(--text-primary)",
                fontSize: 13.5,
                outline: "none",
              }}
            />
            <Button type="submit">Send</Button>
          </form>
        </div>
      </Card>
    </div>
  );
}
